name: Test

on:
  push:
    branches:
      - main
      - master


jobs:
  publish:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: cpdevtools/action-template@dev
        if: ${{ 'a' == 'b' }}
        with: 
          action: init-fork

      - name: Test
        run: ls -al