name: Test

on:
  push:
    branches:
      - main
      - master


jobs:
  publish:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test
        run: ls -al