name: Test

on:
  push:
    branches:
      - "*"
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: ./.github/actions/checkout

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node
