name: Test

on:
  push:
    branches:
      - "*"
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/setup-node
